[harvest]
from = [ "git", "cff",]

[deposit]
mapping = "invenio"
target = "invenio"

[postprocess]
execute = [ "config_record_id",]

[deposit.invenio]
site_url = "https://sandbox.zenodo.org"
access_right = "open"
