on:
  schedule:
    - cron: 37 4 2 * *
  workflow_dispatch:

permissions:
  actions: write
  pull-requests: write
  contents: write

jobs:
  download-from-packagetemplate:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: epiverse-trace/packagetemplate
      - uses: actions/upload-artifact@v4
        with:
          name: config-from-packagetemplate
          path: |
            .Rbuildignore
            .gitattributes
            .gitignore
            .lintr
            .pre-commit-config.yaml
            tests/spelling.R
            tests/testthat/helper-state.R
            tests/testthat/setup-options.R
            tools/check.env
            .github/workflows/

  upload-to-repo:
    runs-on: ubuntu-latest
    needs: download-from-packagetemplate
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: config-from-packagetemplate
      - uses: peter-evans/create-pull-request@v7
        with:
          add-paths: |
            .Rbuildignore
            .gitattributes
            .gitignore
            .lintr
            .pre-commit-config.yaml
            tests/spelling.R
            tests/testthat/helper-state.R
            tests/testthat/setup-options.R
            tools/check.env
            .github/workflows/
